# Generated by Django 3.1.5 on 2021-01-22 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stack',
            new_name='stock',
        ),
    ]
